---
title: "Brexit: A Textual Analysis (Part I)"
output: html_notebook
---
This series of posts explores the language used in the EU [withdrawal bill debate](https://hansard.parliament.uk/lords/2017-03-01/debates/EE9DF3A9-2E05-4568-8CF8-A61F11172391/EuropeanUnion(NotificationOfWithdrawal)Bill). It was motivated by a need to break down the rhetoric into what is important, and see how different groups of speakers within the Lords (whether these be groups from the same party, the same gender etc…) respond differently to the issues. *Why not just read the debate?* I strongly recommend you do indeed read the debate itself. However, text analysis is powerful for several reasons. Firstly, it is time consuming to read a 12 hour debate the whole way through. Secondly, there is simply too much information contained within the debate for a single human mind to efficiently spot all the patterns within the data. As such, text mining offers a way to summarise these meaningful patterns and ideas. 

That is not to say text mining is without problems. By definition, when we summarise the text in some way, we lose information. However, by asking questions that are clear, transparent, and meaningful and being measured about the conclusions we draw, the approach can yield insights that would otherwise be hard to discern. As well as informing people about the Brexit debate, this article also aims to showcase the huge amount of information that can be found in a single structured text file.  

Be sure to use the [glossary](#glossary) at the bottom of the page when you haven’t heard of a term before. If you want to read more about the debates in the Lords or Commons, go to the Government's official website https://hansard.parliament.uk/ or take a look at some of the brilliant work being done at https://www.theyworkforyou.com/

```{r}
plot(cars)
```


### Glossary {#glossary}
#### Crossbench (CB) {#crossbench} 
Crossbench Peers are non-party political and by tradition sit on the benches that cross the chamber of the House of Lords. [source](https://www.parliament.uk/site-information/glossary/crossbench-peers/)

#### Privy Council (PC) {#privycouncil}
A collection of senior politicians who are or have been members of the House of Commons or House of Lords. [source](https://en.wikipedia.org/wiki/Privy_Council_of_the_United_Kingdom)

#### Hansard {#hansard}
A Hansard is the official transcript of proceedings of both the House of Commons and the House of Lords. It is named after Thomas Curson Hansard (1776–1833), a London printer and publisher, who was the first official printer to the parliament at Westminster. [source](https://en.wikipedia.org/wiki/Hansard)
